# Generated by Django 4.0 on 2022-01-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='contributors',
            old_name='user_id',
            new_name='user',
        ),
    ]
