# Generated by Django 4.0 on 2022-01-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_rename_project_id_contributors_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('R', 'read'), ('RW', 'Read_Write'), ('RWD', 'Read_Write_Delete')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('ad', 'admin'), ('te', 'technicien'), ('cu', 'customer')], max_length=20),
        ),
    ]
